SELECT * FROM HR.DEPARTMENTS;
SELECT COUNT(EMPLOYEE_ID) FROM HR.EMPLOYEES WHERE SALARY > 15000;
SELECT COUNT(EMPLOYEE_ID) FROM HR.EMPLOYEES WHERE HIRE_DATE >= '1-JAN-2002' AND HIRE_DATE <= '1-JAN-2005';
SELECT COUNT(EMPLOYEE_ID) FROM HR.EMPLOYEES WHERE PHONE_NUMBER NOT LIKE '515%';
SELECT FIRST_NAME || ' ' || LAST_NAME "NAME" FROM HR.EMPLOYEES WHERE DEPARTMENT_ID =100 ORDER BY FIRST_NAME;
SELECT CITY, STATE_PROVINCE, COUNTRY_NAME FROM HR.COUNTRIES, HR.LOCATIONS WHERE REGION_ID = 3;
SELECT MAX(SALARY) "MAXIMUM", MIN(SALARY) "MINIMUM", SUM(SALARY) "SUM", ROUND(AVG(SALARY)) "AVERAGE" FROM HR.EMPLOYEES;
SELECT * FROM SYS.DUAL;