#!/bin/bash

echo "Your current directory is: "
pwd
echo Your username is $whoami

echo "The version of your shell is : "; bash --version | grep version

echo "Your home directory is : "; echo $HOME
echo "The number of columns in your current terminal is :"; echo $(tput cols) 
